#!/usr/bin/env bash

fastchess \
    -engine name=Pike proto=uci cmd=./pike \
    -engine name=Fruit proto=uci cmd=tests/fruit_21 \
    -openings file=books/8mvs_+90_+99.epd format=epd order=sequential \
    -games 100 \
    -concurrency 1 \
    -each tc=10+0.5 \
    -each proto=uci

