#!/usr/bin/env bash

> t/log.log
fastchess \
    -engine name=pike_new proto=uci cmd=$1 \
    -engine name=pike_old proto=uci cmd=$2 \
    -openings file=books/UHO_Lichess_4852_v1.epd format=epd order=random \
    -games 1000 \
    -concurrency 8 \
    -each tc=0:8+0.08 #\
    #-log file=t/log.log \
    #-log engine=true

