#!/usr/bin/env bash

> tests/log.log
fastchess \
    -engine name=pike_new proto=uci cmd=$1 \
    -engine name=pike_old proto=uci cmd=$2 \
    -openings file=books/8mvs_+90_+99.epd format=epd order=random \
    -games 50 \
    -concurrency 8 \
    -each tc=5+3 \
    -log file=tests/log.log \
    -log engine=true

